POST http://localhost:3001/user/register
Content-Type: application/json

{
    "username": "dsdds",
    "password": "dsds",
    "confirmPassword": "dsds"
}

###
POST http://localhost:3001/login
Content-Type: application/json

{
    "username": "wiktorrudzki",
    "password": "01735b27s32ks82n"
}

###
GET http://localhost:3001/
Content-Type: application/json
